#!/usr/bin/env python3
"""Regenerate gen_icons.py from a directory of simple-icons SVGs.

simple-icons (https://simple-icons.org, CC0-1.0) ships one 24x24 path per brand.
The paths are ~1.5 KB of float noise each, so they are compacted before they are
embedded in a card: numbers are rounded to 2 decimals and a few redundant
commands are collapsed. `build.py` never runs this script — it only reads the
module it writes, so an icon set is a deliberate, committed choice.

    mkdir -p /tmp/si && cd /tmp/si
    for n in python gnubash ...; do
      gh api "repos/simple-icons/simple-icons/contents/icons/$n.svg" \
         --jq .content | base64 -d > "$n.svg"
    done
    python3 tools/profile-art/make_icons.py --src /tmp/si
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# name -> (chip label, colour on graphite)
# Colour is a palette choice, not brand data: several official fills are
# unreadable on #0a1017 (Lua is #000080, Gradle #02303A, CMake #064A80, mpv and
# ffmpeg are near-black), so dark brands are lifted to the nearest legible tint.
WANTED = {
    # name                 label              colour on graphite  tile
    "python":              ("Python",         "#4B8BBE", "Py"),
    "gnubash":             ("Bash",            "#89E051", "$"),
    "openjdk":             ("Java",            "#F89820", "Jv"),
    "kotlin":              ("Kotlin",          "#A97BFF", "Kt"),
    "androidstudio":       ("Android Studio",  "#3DDC84", "As"),
    "gradle":              ("Gradle",          "#6FCFFF", "Gr"),
    "jetpackcompose":      ("Jetpack Compose", "#34A853", "Cp"),
    "cmake":               ("CMake",           "#6CB8F5", "Ck"),
    "android":             ("ADB",             "#3DDC84", "Ad"),
    "linux":               ("Linux",           "#FCC624", "Lx"),
    "mpv":                 ("mpv",             "#C39BFF", "Mv"),
    "ffmpeg":              ("ffmpeg",          "#FF5C7A", "Ff"),
    "git":                 ("Git",             "#F05032", "Gt"),
    "github":              ("GitHub",          "#E6EDF3", "GH"),
    "githubactions":       ("GitHub Actions",  "#2088FF", "Ac"),
    "claude":              ("Claude Code",     "#D97757", "Cl"),
    "googlegemini":        ("Gemini CLI",      "#4285F4", "Gm"),
    "telegram":            ("Telegram",        "#22A7E0", "Tg"),
    "vercel":              ("Vercel",          "#FFFFFF", "Vc"),
    "githubsponsors":      ("GitHub Sponsors", "#F472B6", "$"),
}
# brands with no glyph upstream any more (simple-icons dropped Termux): drawn as
# a mono tile instead, which is what the card did before brand icons existed.
# …and marks that read as a blob at chip size are drawn as tiles on purpose, even
# though a path exists upstream (Lua is a hairline crescent, Rust a gear full of
# holes — both need ~28px before they say anything).
FALLBACK = {"termux": ("Termux", "#4ADE80", "Tx"),
            "ndk":    ("NDK", "#3DDC84", "Nd"),
            "lua":    ("Lua", "#7C8FFF", "Lu"),
            "rust":   ("Rust", "#FF7043", "Rs"),
            # a gist is not a brand, so it gets the braces: the shortest honest
            # drawing of "a file of code" that survives at 24px
            "gists":  ("Gists", "#FBBF24", "{}")}


def num(m):
    v = float(m.group(0))
    r = round(v, 2)
    return f"{r:g}"


def compact(d):
    d = re.sub(r"-\s*-\s*", "-", d)                 # "- -5" -> "-5"
    d = re.sub(r"-0\.", "-.", d)
    d = re.sub(r"(?<![\d.])0\.", ".", d)
    d = re.sub(r"\d+\.\d{3,}", num, d)               # 12.345678 -> 12.35
    d = re.sub(r"\s*,\s*", ",", d)
    d = re.sub(r"\s+(-)", r" \1", d)
    d = re.sub(r"\s{2,}", " ", d).strip()
    return d


def extract(path):
    s = open(path, encoding="utf-8").read()
    m = re.search(r'<path[^>]*\bd="([^"]+)"', s)
    if not m:
        raise SystemExit(f"no single <path> in {path}")
    vb = re.search(r'viewBox="([^"]+)"', s)
    box = [float(x) for x in vb.group(1).split()] if vb else [0, 0, 24, 24]
    return box, compact(m.group(1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="/tmp/si", help="directory of downloaded *.svg files")
    ap.add_argument("--out", default=os.path.join(HERE, "gen_icons.py"))
    args = ap.parse_args()

    entries = []
    for name, (label, color, tile) in WANTED.items():
        src = os.path.join(args.src, f"{name}.svg")
        if not os.path.exists(src):
            print(f"  ! {name}: no {src}, falling back to a mono tile")
            continue
        box, d = extract(src)
        scale = 24.0 / box[2]
        entries.append((name, label, color, tile, round(scale, 4), d))
    for name, (label, color, tile) in FALLBACK.items():
        entries.append((name, label, color, tile, 1.0, ""))

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write('"""Brand glyphs for the stack card.\n\n'
                 'Generated by `make_icons.py` from simple-icons (CC0-1.0, https://simple-icons.org).\n'
                 'Every path is a 24x24 icon: `scale` is the ratio applied so a non-24 viewBox still\n'
                 'lands on the 24 grid, and `d` is the path data with its floats rounded to 2 decimals.\n'
                 'A brand with an empty `d` (termux) has no glyph upstream and is drawn as a mono tile.\n\n'
                 'Do not hand-edit the path data — re-run the generator.\n"""\n\n')
        fh.write("ICONS = {\n")
        for name, label, color, tile, scale, d in entries:
            row = f'    {name!r}: {{"label": {label!r}, "color": {color!r}, '
            row += f'"tile": {tile!r}, "scale": {scale}, "d": {d!r}}},\n'
            fh.write(row)
        fh.write("}\n")

    total = os.path.getsize(args.out)
    print(f"wrote {args.out}: {len(entries)} icons, {total / 1024:.1f} KB")


if __name__ == "__main__":
    main()
